CREATE DATABASE BDALMACEN;
USE BDALMACEN;
--//---- USUARIO-//--

CREATE TABLE GENERO(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(15)NOT NULL,
);

CREATE TABLE ROL_USUARIO( 
ID INT PRIMARY KEY,
NOMBRE VARCHAR(15)NOT NULL,
);

CREATE TABLE ESTADO_USUARIO(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(15)NOT NULL,
);

CREATE TABLE DEPARTAMENTOS(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(50)NOT NULL,
);

CREATE TABLE USUARIO(
CODINTERNO BIGINT ,
NODOCUMENTO BIGINT NOT NULL,
PASSWORD VARCHAR(15)NOT NULL,
NOMBRES VARCHAR(45)NOT NULL,
APELLIDOS VARCHAR(45)NOT NULL,
IDGENERO INT NOT NULL,
IDROLUSUARIO INT NOT NULL,
IDESTADOUSUARIO INT NOT NULL,
MOVIL BIGINT NULL,
TELEFONO BIGINT NULL,
EMAIL VARCHAR(50) NULL,
IDDEPARTAMENTO INT NOT NULL,
CIUDAD VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(50) NULL ,
CONSTRAINT PK_USUARIO PRIMARY KEY(CODINTERNO),
CONSTRAINT UK_USUARIO UNIQUE(NODOCUMENTO),
CONSTRAINT FK_USUARIO_IDROLUSUARIO FOREIGN KEY (IDROLUSUARIO) REFERENCES ROL_USUARIO(ID),
CONSTRAINT FK_USUARIO_IDESTADOUSUARIO FOREIGN KEY (IDESTADOUSUARIO) REFERENCES ESTADO_USUARIO(ID),
CONSTRAINT FK_USUARIO_IDDEPARTAMENTO FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID),
CONSTRAINT FK_USUARIO_IDGENERO FOREIGN KEY (IDGENERO) REFERENCES GENERO(ID),
);


CREATE TABLE CLIENTE(
CODINTERNO BIGINT,
NODOCUMENTO BIGINT NOT NULL,
NOMBRES VARCHAR(45) NOT NULL,
APELLIDOS VARCHAR(45) NOT NULL,
IDGENERO INT NOT NULL,
MOVIL BIGINT NULL,
TELEFONO BIGINT NULL,
CIUDAD VARCHAR(50) NULL,
DIRECCION VARCHAR(50) NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY(CODINTERNO),
CONSTRAINT UK_CLIENTE UNIQUE(NODOCUMENTO),
CONSTRAINT FK_CLIENTE_IDGENERO FOREIGN KEY (IDGENERO) REFERENCES GENERO(ID),
);


------------------------------PRODUCTO Y PROVEEDOR--------------------------------------------------
GO
CREATE TABLE UNIDAD_PRODUCTO(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
);
GO
CREATE TABLE CATEGORIA_PRODUCTO(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
);
   
GO 
CREATE TABLE MARCA(
ID INT PRIMARY KEY ,
NOMBRE VARCHAR(45) NOT NULL,
);

GO
CREATE TABLE PROVEEDOR(
CODINTERNO BIGINT,
IDPROVEEDOR BIGINT NOT NULL,
NOMBRE VARCHAR(45)NOT NULL,
DIRECCION VARCHAR(50)NOT NULL,
TELEFONO BIGINT NOT NULL,
EMAIL VARCHAR(50) NULL,
RUT BIGINT NULL,
NOMBRECONTACTO VARCHAR(45)NOT NULL,
TELEFONOCONTACTO BIGINT NULL,
EMAILCONTACTO VARCHAR(50),
IDDEPARTAMENTO INT NOT NULL ,
CIUDAD VARCHAR(50)NOT NULL,
NOTAS VARCHAR(150) NULL,
CONSTRAINT PK_PROVEEDOR PRIMARY KEY(CODINTERNO),
CONSTRAINT UK_PROVEEDOR UNIQUE(IDPROVEEDOR),
CONSTRAINT FK_PROVEEDOR_IDDEPARTAMENTO FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID),
);


GO
CREATE TABLE PRODUCTO(
CODINTERNO BIGINT NOT NULL,
IDPRODUCTO BIGINT NOT NULL,
IDPROVEEDOR BIGINT NOT NULL,
IDCATEGORIA INT NOT NULL ,
IDUNIDADPRODUCTO INT NOT NULL,
IDMARCA INT NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL,
STOCKINICIAL INT NOT NULL,
STOCKACTUAL INT NOT NULL,
PRECIOUNITARIO DECIMAL(20) NOT NULL,
IVA INT NOT NULL,
PRECIOIVA  DECIMAL(20) NOT NULL,
CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODINTERNO) ,
CONSTRAINT UK_PRODUCTO UNIQUE(IDPRODUCTO),
CONSTRAINT FK_PRODUCTO_IDCATEGORIA FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA_PRODUCTO(ID),
CONSTRAINT FK_PRODUCTO_IDMARCA FOREIGN KEY(IDMARCA) REFERENCES MARCA(ID),
CONSTRAINT FK_PRODUCTO_IDPROVEEDOR FOREIGN KEY(IDPROVEEDOR) REFERENCES PROVEEDOR(IDPROVEEDOR),
CONSTRAINT FK_PRODUCTO_IDUNIDADPRODUCTO FOREIGN KEY(IDUNIDADPRODUCTO) REFERENCES UNIDAD_PRODUCTO(ID),
);

GO
CREATE TABLE IVA(
ID INT NOT NULL,
IVA BIGINT NOT NULL,
);

-------------------------------FACTURACION------------------------------------------------------------

GO
CREATE TABLE FACTURA(
NOFACTURA BIGINT NOT NULL,
IDCLIENTE BIGINT NOT NULL,
IVA INT NOT NULL,
SUBTOTAL DECIMAL(20) NOT NULL ,
TOTALPAGAR DECIMAL(20)NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT PK_FACTURA PRIMARY KEY(NOFACTURA),
);

CREATE TABLE DETALLEFACTURA
(
NOFACTURA BIGINT,
IDPRODUCTO BIGINT NOT NULL,
DESCUENTO INT NOT NULL,
CANTIDAD  INT NOT NULL,
CONSTRAINT PK_DETALLEFACTURA PRIMARY KEY (NOFACTURA,IDPRODUCTO),
CONSTRAINT FK_DETALLEFACTURA_IDPRODUCTO FOREIGN KEY(IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO),
CONSTRAINT FK_DETALLEFACTURA_NOFACTURA FOREIGN KEY (NOFACTURA) REFERENCES FACTURA(NOFACTURA),
);
-------------------------------AUDITORIA------------------------------------------------------------
CREATE TABLE AUDITORIALOGIN
(
ID INT,
IDCODINTERNO BIGINT NOT NULL,
HORAINICIO TIME NOT NULL,
HORAFIN TIME NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT PK_AUDITORIALOGIN PRIMARY KEY (ID),
CONSTRAINT FK_AUDITORIALOGIN_IDCODINTERNO FOREIGN KEY (IDCODINTERNO) REFERENCES USUARIO(CODINTERNO),
)

CREATE TABLE AUDITORIAFACTURA
(
ID INT IDENTITY NOT NULL,
NOFACTURA BIGINT NOT NULL,
NODOCUMENTO BIGINT NOT NULL,
CONSTRAINT PK_AUDITORIAFACTURA PRIMARY KEY (ID),
CONSTRAINT FK_AUDITORIAFACTURA_NOFACTURA FOREIGN KEY (NOFACTURA) REFERENCES FACTURA(NOFACTURA),
CONSTRAINT FK_AUDITORIAFACTURA_NODOCUMENTO FOREIGN KEY (NODOCUMENTO) REFERENCES USUARIO(NODOCUMENTO),
); 


-------------------------------PROCEDIMIENTOS ALMACENADOS--------------------------------------------

CREATE PROCEDURE CONTROLSESION
AS
SELECT TOP 1 ID FROM AUDITORIALOGIN ORDER BY ID DESC
----------------------------------------------------------------------------------------------------
CREATE PROCEDURE ULTIMASSESIONES
@IDCODINTERNO BIGINT
AS
SELECT TOP 10 HORAINICIO,HORAFIN,FECHA
FROM AUDITORIALOGIN
WHERE IDCODINTERNO=@IDCODINTERNO
ORDER BY (Fecha) DESC
-----------------------------------------------------------------------------------------------------
CREATE PROCEDURE CONSULTARSTOCKPRODUCTO
AS
SELECT PRO.CODINTERNO AS CODINTERNO ,PRO.IDPRODUCTO AS IDPRODUCTO ,PROV.NOMBRE AS NOMBREPROVEDOR , CATEGORIA.NOMBRE AS CATEGORIA,UNIDAD.NOMBRE AS CANTIDAD , MARCA.NOMBRE AS MARCA ,PRO.DESCRIPCION,PRO.STOCKINICIAL,PRO.STOCKACTUAL,PRO.PRECIOUNITARIO,PRO.IVA ,PRO.PRECIOIVA
FROM PRODUCTO AS PRO ,MARCA,PROVEEDOR AS PROV,CATEGORIA_PRODUCTO AS CATEGORIA,UNIDAD_PRODUCTO AS UNIDAD
WHERE MARCA.ID = PRO.IDMARCA and PRO.IDPROVEEDOR = PROV.IDPROVEEDOR AND CATEGORIA.ID = PRO.IDCATEGORIA AND UNIDAD.ID = PRO.IDUNIDADPRODUCTO
-----------------------------------------------------------------------------------------------------
CREATE PROCEDURE CONSULTARSTOCKID
@IDPRODUCTO BIGINT
AS
SELECT PRO.CODINTERNO AS CODINTERNO ,PRO.IDPRODUCTO AS IDPRODUCTO ,PROV.NOMBRE AS NOMBREPROVEDOR , CATEGORIA.NOMBRE AS CATEGORIA,UNIDAD.NOMBRE AS CANTIDAD , MARCA.NOMBRE AS MARCA ,PRO.DESCRIPCION,PRO.STOCKINICIAL,PRO.STOCKACTUAL,PRO.PRECIOUNITARIO,PRO.IVA ,PRO.PRECIOIVA
FROM PRODUCTO AS PRO ,MARCA,PROVEEDOR AS PROV,CATEGORIA_PRODUCTO AS CATEGORIA,UNIDAD_PRODUCTO AS UNIDAD
WHERE MARCA.ID = PRO.IDMARCA and PRO.IDPROVEEDOR = PROV.IDPROVEEDOR AND CATEGORIA.ID = PRO.IDCATEGORIA AND UNIDAD.ID = PRO.IDUNIDADPRODUCTO AND PRO.IDPRODUCTO = @IDPRODUCTO
-----------------------------------------------------------------------------------------------------
CREATE PROCEDURE CONSULTARLOGIN
@NODOCUMENTO BIGINT
AS
SELECT AUDITORIALOGIN.ID ,AUDITORIALOGIN.IDCODINTERNO,USUARIO.NODOCUMENTO AS DOCUMENTO,AUDITORIALOGIN.HORAINICIO,AUDITORIALOGIN.HORAFIN,AUDITORIALOGIN.FECHA
FROM AUDITORIALOGIN,USUARIO
WHERE AUDITORIALOGIN.IDCODINTERNO = USUARIO.CODINTERNO AND USUARIO.NODOCUMENTO=@NODOCUMENTO
------------------------------------------------------------------------------------------------------
CREATE PROCEDURE CONSULTARFACTURA
@NODOCUMENTO BIGINT
AS
SELECT FACTURA.NOFACTURA,FACTURA.IDCLIENTE,FACTURA.IVA,FACTURA.SUBTOTAL,FACTURA.TOTALPAGAR,FACTURA.FECHA
FROM FACTURA,AUDITORIAFACTURA
WHERE AUDITORIAFACTURA.NOFACTURA = FACTURA.NOFACTURA AND AUDITORIAFACTURA.NODOCUMENTO=@NODOCUMENTO
------------------------------------------------------------------------------------------------------

CREATE PROCEDURE CONSULTARDETALLEFACTURA
@NOFACTURA BIGINT
AS
SELECT DETALLEFACTURA.NOFACTURA ,PRODUCTO.DESCRIPCION,DETALLEFACTURA.DESCUENTO,DETALLEFACTURA.CANTIDAD
FROM DETALLEFACTURA,FACTURA,PRODUCTO,MARCA
WHERE DETALLEFACTURA.NOFACTURA = FACTURA.NOFACTURA AND DETALLEFACTURA.IDPRODUCTO = PRODUCTO.IDPRODUCTO AND DETALLEFACTURA.NOFACTURA = @NOFACTURA
------------------------------------------------------------------------------------------------------
CREATE PROCEDURE CAMBIARPASSWORD
@NODOCUMENTO BIGINT,
@PASSWORD VARCHAR(15)
AS
IF EXISTS(SELECT PASSWORD FROM USUARIO WHERE NODOCUMENTO=@NODOCUMENTO)
BEGIN
 UPDATE USUARIO SET PASSWORD =@PASSWORD
END
----------------------------------------------------------------------------------------------------
CREATE PROCEDURE CODINTERNOUSUARIO
AS
SELECT TOP 1 CODINTERNO FROM USUARIO ORDER BY CODINTERNO DESC
----------------------------------------------------------------------------------------------------
CREATE PROCEDURE CODINTERNOCLIENTE
AS
SELECT TOP 1 CODINTERNO FROM CLIENTE ORDER BY CODINTERNO DESC
----------------------------------------------------------------------------------------------------
CREATE PROCEDURE CODINTERNOPROVEEDOR
AS
SELECT TOP 1 CODINTERNO FROM PROVEEDOR ORDER BY CODINTERNO DESC
----------------------------------------------------------------------------------------------------
CREATE PROCEDURE CODINTERNOPRODUCTO
AS
SELECT TOP 1 CODINTERNO FROM PRODUCTO ORDER BY CODINTERNO DESC
----------------------------------------------------------------------------------------------------
CREATE PROCEDURE CODINTERNOFACTURA
AS
SELECT TOP 1 NOFACTURA FROM FACTURA ORDER BY NOFACTURA DESC
----------------------------------------------------------------------------------------------------
CREATE PROCEDURE CONSULTARIVA
AS
SELECT TOP 1 IVA FROM IVA ORDER BY ID DESC
----------------------------------------------------------------------------------------------------
CREATE PROCEDURE ULTIMAORDEN
AS
SELECT TOP 1 ORDEN FROM TICKET ORDER BY ORDEN DESC
----------------------------------------------------------------------------------------------------
CREATE PROCEDURE INSERTARDETALLEFACTURA
@NOFACTURA BIGINT,
@IDPRODUCTO BIGINT,
@DESCUENTO INT,
@CANTIDAD INT
AS
IF NOT EXISTS (SELECT * FROM FACTURA WHERE NOFACTURA=@NOFACTURA)
BEGIN
   PRINT 'NO EXISTE LA FACTURA'
END
ELSE
IF NOT EXISTS (SELECT * FROM PRODUCTO WHERE IDPRODUCTO=@IDPRODUCTO )
BEGIN 
 PRINT 'EL PRODUCTO NO EXSTE'
END
ELSE
IF EXISTS (SELECT @NOFACTURA,@IDPRODUCTO,@DESCUENTO,@CANTIDAD FROM DETALLEFACTURA  WHERE NOFACTURA=@NOFACTURA AND IDPRODUCTO=@IDPRODUCTO  AND DESCUENTO=@DESCUENTO AND CANTIDAD=@CANTIDAD)
BEGIN 
 PRINT 'ESTE DETALLE DE FACTURA YA EXISTE'
 END
 ELSE
 BEGIN
   INSERT INTO DETALLEFACTURA VALUES(@NOFACTURA,@IDPRODUCTO,@DESCUENTO,@CANTIDAD)
   UPDATE PRODUCTO SET STOCKACTUAL =STOCKACTUAL-@CANTIDAD WHERE IDPRODUCTO=@IDPRODUCTO AND STOCKACTUAL > @CANTIDAD
 END
----------------------------------------------------------------------------------------------------

--//---INSERTS GENERO--////---

INSERT INTO GENERO
VALUES (1,'Masculino'), (2,'Femenino'),(3,'Otros')

---//INSERT TIPO USUARIO --//--

INSERT INTO ROL_USUARIO
VALUES (1,'Administrador'),(2,'Operador')

--//INSERT ESTADO USUARIO--//--

INSERT INTO ESTADO_USUARIO
VALUES (1,'Habilitado'),(2,'Bloqueado')

--// INSERT INTO DEPARTAMENTO-//

INSERT INTO DEPARTAMENTOS
VALUES 
(1,52,'Amazonas'),(2,52,'Antioquia'),(3,52,'Arauca'),(4,52,'Atlántico'),
(5,52,'Bolívar'), (6,52,'Boyacá'), (7,52,'Caldas'),(8,52,'Caquetá'),
(9,52,'Casanare'),(10,52,'Cauca'),(11,52,'Cesar'),(12,52,'Chocó'),
(13,52,'Córdoba'),(14,52,'Cundinamarca'),(15,52,'Güainia'),(16,52,'Guaviare'),
(17,52,'Huila'),(18,52,'La Guajira'),(19,52,'Magdalena'),(20,52,'Meta'),
(21,52,'Nariño'),(22,52,'Norte de Santander'),(23,52,'Putumayo'),(24,52,'Quindo'),
(25,52,'Risaralda'),(26,52,'San Andrés y Providencia'),(27,52,'Santander'),(28,52,'Sucre'),
(29,52,'Tolima'),(30,52,'Valle del Cauca'),(31,52,'Vaupés'),(32,52,'Vichada');
--//INSERT ESTADO AUDITORIALOGIN--//--

INSERT INTO USUARIO(CODINTERNO,NODOCUMENTO,PASSWORD,NOMBRES,APELLIDOS,IDGENERO,IDROLUSUARIO,IDESTADOUSUARIO,IDDEPARTAMENTO,CIUDAD)VALUES(0,1042447888,3729190,'Adrian','Amaris',1,3,1,4,'Barranquilla')
INSERT INTO AUDITORIALOGIN(ID,IDCODINTERNO,HORAINICIO,HORAFIN,FECHA)VALUES(0,0,'00:00','00:00', CONVERT(VARCHAR(10), GETDATE(), 103))
INSERT INTO IVA(ID,IVA)VALUES(1,119)




INSERT INTO departamento
VALUES 
(1,52,91,'CO-AMA','Amazonas'),(2,52,05,'CO-ANT','Antioquia'),(3,52,81,'CO-ARA','Arauca'),(4,52,08,'CO-ATL','Atlántico'),
(5,52,11,'CO-DC','Bogota Dc')
(6,52,13,'CO-BOL','Bolívar'), (7,52,15,'CO-BOY','Boyacá'), (8,52,17,'CO-CAL','Caldas'),(9,52,18,'CO-CAQ','Caquetá'),
(10,52,25,'CO-CAS','Casanare'),(11,52,19,'CO-CAU','Cauca'),(12,52,20,'CO-CES','Cesar'),(13,52,27,'CO-CHO','Chocó'),
(14,52,23,'CO-COR','Córdoba'),(15,52,25,'CO-CUN','Cundinamarca'),(16,52,94,'CO-GUA','Güainia'),(17,52,95,'CO-GUV','Guaviare'),
(18,52,41,'CO-HUI','Huila'),(19,52,44,'CO-LAG','La Guajira'),(20,52,47,'CO-MAG','Magdalena'),(21,52,50,'CO-MET','Meta'),
(22,52,52,'CO-NAR','Nariño'),(23,52,54,'CO-NSA','Norte de Santander'),(24,52,86,'CO-PUT','Putumayo'),(25,52,63,'CO-QUI','Quindo'),
(26,52,66,'CO-RIS','Risaralda'),(27,52,88,'CO-SAP','San Andrés y Providencia'),(28,52,68,'CO-SAN','Santander'),(29,52,70,'CO-SUC','Sucre'),
(30,52,73,'CO-TOL','Tolima'),(31,52,76,'CO-VAC','Valle del Cauca'),(32,52,97,'CO-VAU','Vaupés'),(33,52,99,'CO-VID','Vichada');



select * from AUDITORIALOGIN
select * from FACTURA
select * from detallefactura
delete from FACTURA